# Generated by gallery/generate.py; do not edit.
function productivemetalworks_gallery:clear
# stock-control: stone stock rendering control
setblock 176 100 175 minecraft:stone
function productivemetalworks_gallery:verify
