# Generated by gallery/generate.py; do not edit.
function productivemetalworks_gallery:clear
# table-empty: empty casting table
setblock 160 100 160 productivemetalworks:casting_table[facing=north]
# table-filled: half-full casting table
setblock 162 100 160 productivemetalworks:casting_table[facing=north]{fluid:{Fluid:{id:"productivemetalworks:molten_iron",amount:500}},maxAmount:1000,coolingTime:0}
# basin-filled: three-quarter casting basin
setblock 164 100 160 productivemetalworks:casting_basin[facing=north]{fluid:{Fluid:{id:"productivemetalworks:molten_iron",amount:750}},maxAmount:1000,coolingTime:0}
# tank-empty: empty red tank
setblock 166 100 160 productivemetalworks:red_foundry_tank[facing=north]
# tank-half: half-full blue tank
setblock 168 100 160 productivemetalworks:blue_foundry_tank[facing=north]{fluid:{Fluid:{id:"productivemetalworks:molten_copper",amount:2000}}}
# tank-full: full green tank
setblock 170 100 160 productivemetalworks:green_foundry_tank[facing=north]{fluid:{Fluid:{id:"productivemetalworks:molten_emerald",amount:4000}}}
# capacitor-empty: empty black capacitor
setblock 160 100 163 productivemetalworks:black_foundry_capacitor[facing=north]{energy:0}
# capacitor-half: half-full red capacitor
setblock 162 100 163 productivemetalworks:red_foundry_capacitor[facing=north]{energy:20000}
# capacitor-full: full green capacitor
setblock 164 100 163 productivemetalworks:green_foundry_capacitor[facing=north]{energy:40000}
# tap-basin: active tap destination basin
setblock 168 100 163 productivemetalworks:casting_basin[facing=north]{fluid:{Fluid:{id:"productivemetalworks:molten_iron",amount:750}},maxAmount:1000,coolingTime:0}
# tap-active: active molten tap
setblock 168 101 163 productivemetalworks:foundry_tap[facing=north]{isActive:1b,fluidId:1}
# molten-iron: molten iron tint
setblock 160 100 166 productivemetalworks:molten_iron
# molten-emerald: molten emerald tint
setblock 162 100 166 productivemetalworks:molten_emerald
# molten-redstone: molten redstone tint
setblock 164 100 166 productivemetalworks:molten_redstone
# molten-refined-obsidian: molten refined obsidian tint
setblock 166 100 166 productivemetalworks:molten_refined_obsidian
# window-red-lower: mixed window red lower
setblock 169 100 166 productivemetalworks:red_foundry_window[facing=north]
# window-blue-lower: mixed window blue lower
setblock 170 100 166 productivemetalworks:blue_foundry_window[facing=north]
# window-green-upper: mixed window green upper
setblock 169 101 166 productivemetalworks:green_foundry_window[facing=north]
# window-yellow-upper: mixed window yellow upper
setblock 170 101 166 productivemetalworks:yellow_foundry_window[facing=north]
function productivemetalworks_gallery:verify
