# Generated by gallery/generate.py; do not edit.
execute unless block 160 100 160 productivemetalworks:casting_table[facing=north] run tellraw @a {"text":"gallery mismatch: table-empty","color":"red"}
execute unless block 162 100 160 productivemetalworks:casting_table[facing=north] run tellraw @a {"text":"gallery mismatch: table-filled","color":"red"}
execute unless block 164 100 160 productivemetalworks:casting_basin[facing=north] run tellraw @a {"text":"gallery mismatch: basin-filled","color":"red"}
execute unless block 166 100 160 productivemetalworks:red_foundry_tank[facing=north] run tellraw @a {"text":"gallery mismatch: tank-empty","color":"red"}
execute unless block 168 100 160 productivemetalworks:blue_foundry_tank[facing=north] run tellraw @a {"text":"gallery mismatch: tank-half","color":"red"}
execute unless block 170 100 160 productivemetalworks:green_foundry_tank[facing=north] run tellraw @a {"text":"gallery mismatch: tank-full","color":"red"}
execute unless block 160 100 163 productivemetalworks:black_foundry_capacitor[facing=north] run tellraw @a {"text":"gallery mismatch: capacitor-empty","color":"red"}
execute unless block 162 100 163 productivemetalworks:red_foundry_capacitor[facing=north] run tellraw @a {"text":"gallery mismatch: capacitor-half","color":"red"}
execute unless block 164 100 163 productivemetalworks:green_foundry_capacitor[facing=north] run tellraw @a {"text":"gallery mismatch: capacitor-full","color":"red"}
execute unless block 168 100 163 productivemetalworks:casting_basin[facing=north] run tellraw @a {"text":"gallery mismatch: tap-basin","color":"red"}
execute unless block 168 101 163 productivemetalworks:foundry_tap[facing=north] run tellraw @a {"text":"gallery mismatch: tap-active","color":"red"}
execute unless block 160 100 166 productivemetalworks:molten_iron run tellraw @a {"text":"gallery mismatch: molten-iron","color":"red"}
execute unless block 162 100 166 productivemetalworks:molten_emerald run tellraw @a {"text":"gallery mismatch: molten-emerald","color":"red"}
execute unless block 164 100 166 productivemetalworks:molten_redstone run tellraw @a {"text":"gallery mismatch: molten-redstone","color":"red"}
execute unless block 166 100 166 productivemetalworks:molten_refined_obsidian run tellraw @a {"text":"gallery mismatch: molten-refined-obsidian","color":"red"}
execute unless block 169 100 166 productivemetalworks:red_foundry_window[facing=north] run tellraw @a {"text":"gallery mismatch: window-red-lower","color":"red"}
execute unless block 170 100 166 productivemetalworks:blue_foundry_window[facing=north] run tellraw @a {"text":"gallery mismatch: window-blue-lower","color":"red"}
execute unless block 169 101 166 productivemetalworks:green_foundry_window[facing=north] run tellraw @a {"text":"gallery mismatch: window-green-upper","color":"red"}
execute unless block 170 101 166 productivemetalworks:yellow_foundry_window[facing=north] run tellraw @a {"text":"gallery mismatch: window-yellow-upper","color":"red"}
tellraw @a {"text":"Productive Metalworks gallery checked","color":"green"}
